// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecommendedtopicsRouteImport } from './routes/recommendedtopics'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewtopicsRouteImport } from './routes/newtopics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BoardlistRouteImport } from './routes/boardlist'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicTopicIdRouteImport } from './routes/topic/$topicId'
import { Route as BoardBoardIdRouteImport } from './routes/board/$boardId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedUsercenterRouteImport } from './routes/_authenticated/usercenter'
import { Route as AuthenticatedNewTopicRouteImport } from './routes/_authenticated/new-topic'
import { Route as AuthenticatedMessageRouteImport } from './routes/_authenticated/message'
import { Route as AuthenticatedFollowingTopicsRouteImport } from './routes/_authenticated/following-topics'
import { Route as AuthenticatedFollowingRouteImport } from './routes/_authenticated/following'
import { Route as AuthenticatedUsercenterIndexRouteImport } from './routes/_authenticated/usercenter.index'
import { Route as AuthenticatedMessageIndexRouteImport } from './routes/_authenticated/message.index'
import { Route as AuthenticatedFollowingIndexRouteImport } from './routes/_authenticated/following.index'
import { Route as UserIdIdRouteImport } from './routes/user/id/$id'
import { Route as AuthenticatedUsercenterTransferRouteImport } from './routes/_authenticated/usercenter.transfer'
import { Route as AuthenticatedUsercenterThemeRouteImport } from './routes/_authenticated/usercenter.theme'
import { Route as AuthenticatedUsercenterSigninRouteImport } from './routes/_authenticated/usercenter.signin'
import { Route as AuthenticatedUsercenterFollowedBoardsRouteImport } from './routes/_authenticated/usercenter.followed-boards'
import { Route as AuthenticatedUsercenterFansRouteImport } from './routes/_authenticated/usercenter.fans'
import { Route as AuthenticatedUsercenterEditRouteImport } from './routes/_authenticated/usercenter.edit'
import { Route as AuthenticatedMessageSystemRouteImport } from './routes/_authenticated/message.system'
import { Route as AuthenticatedMessageReplyRouteImport } from './routes/_authenticated/message.reply'
import { Route as AuthenticatedMessagePrivateRouteImport } from './routes/_authenticated/message.private'
import { Route as AuthenticatedMessageAtRouteImport } from './routes/_authenticated/message.at'
import { Route as AuthenticatedFollowingUsersRouteImport } from './routes/_authenticated/following.users'
import { Route as AuthenticatedFollowingBoardsRouteImport } from './routes/_authenticated/following.boards'
import { Route as TopicTopicIdTraceUserIdRouteImport } from './routes/topic/$topicId/trace/$userId'
import { Route as AuthenticatedUsercenterMytopicsPageRouteImport } from './routes/_authenticated/usercenter.mytopics.$page'
import { Route as AuthenticatedUsercenterMypostsPageRouteImport } from './routes/_authenticated/usercenter.myposts.$page'
import { Route as AuthenticatedUsercenterFavoritesPageRouteImport } from './routes/_authenticated/usercenter.favorites.$page'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendedtopicsRoute = RecommendedtopicsRouteImport.update({
  id: '/recommendedtopics',
  path: '/recommendedtopics',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewtopicsRoute = NewtopicsRouteImport.update({
  id: '/newtopics',
  path: '/newtopics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardlistRoute = BoardlistRouteImport.update({
  id: '/boardlist',
  path: '/boardlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsercenterRoute = AuthenticatedUsercenterRouteImport.update({
  id: '/usercenter',
  path: '/usercenter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewTopicRoute = AuthenticatedNewTopicRouteImport.update({
  id: '/new-topic',
  path: '/new-topic',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessageRoute = AuthenticatedMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFollowingTopicsRoute =
  AuthenticatedFollowingTopicsRouteImport.update({
    id: '/following-topics',
    path: '/following-topics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFollowingRoute = AuthenticatedFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsercenterIndexRoute =
  AuthenticatedUsercenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)
const AuthenticatedMessageIndexRoute =
  AuthenticatedMessageIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessageRoute,
  } as any)
const AuthenticatedFollowingIndexRoute =
  AuthenticatedFollowingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFollowingRoute,
  } as any)
const UserIdIdRoute = UserIdIdRouteImport.update({
  id: '/user/id/$id',
  path: '/user/id/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsercenterTransferRoute =
  AuthenticatedUsercenterTransferRouteImport.update({
    id: '/transfer',
    path: '/transfer',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)
const AuthenticatedUsercenterThemeRoute =
  AuthenticatedUsercenterThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)
const AuthenticatedUsercenterSigninRoute =
  AuthenticatedUsercenterSigninRouteImport.update({
    id: '/signin',
    path: '/signin',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)
const AuthenticatedUsercenterFollowedBoardsRoute =
  AuthenticatedUsercenterFollowedBoardsRouteImport.update({
    id: '/followed-boards',
    path: '/followed-boards',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)
const AuthenticatedUsercenterFansRoute =
  AuthenticatedUsercenterFansRouteImport.update({
    id: '/fans',
    path: '/fans',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)
const AuthenticatedUsercenterEditRoute =
  AuthenticatedUsercenterEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)
const AuthenticatedMessageSystemRoute =
  AuthenticatedMessageSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedMessageRoute,
  } as any)
const AuthenticatedMessageReplyRoute =
  AuthenticatedMessageReplyRouteImport.update({
    id: '/reply',
    path: '/reply',
    getParentRoute: () => AuthenticatedMessageRoute,
  } as any)
const AuthenticatedMessagePrivateRoute =
  AuthenticatedMessagePrivateRouteImport.update({
    id: '/private',
    path: '/private',
    getParentRoute: () => AuthenticatedMessageRoute,
  } as any)
const AuthenticatedMessageAtRoute = AuthenticatedMessageAtRouteImport.update({
  id: '/at',
  path: '/at',
  getParentRoute: () => AuthenticatedMessageRoute,
} as any)
const AuthenticatedFollowingUsersRoute =
  AuthenticatedFollowingUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedFollowingRoute,
  } as any)
const AuthenticatedFollowingBoardsRoute =
  AuthenticatedFollowingBoardsRouteImport.update({
    id: '/boards',
    path: '/boards',
    getParentRoute: () => AuthenticatedFollowingRoute,
  } as any)
const TopicTopicIdTraceUserIdRoute = TopicTopicIdTraceUserIdRouteImport.update({
  id: '/trace/$userId',
  path: '/trace/$userId',
  getParentRoute: () => TopicTopicIdRoute,
} as any)
const AuthenticatedUsercenterMytopicsPageRoute =
  AuthenticatedUsercenterMytopicsPageRouteImport.update({
    id: '/mytopics/$page',
    path: '/mytopics/$page',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)
const AuthenticatedUsercenterMypostsPageRoute =
  AuthenticatedUsercenterMypostsPageRouteImport.update({
    id: '/myposts/$page',
    path: '/myposts/$page',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)
const AuthenticatedUsercenterFavoritesPageRoute =
  AuthenticatedUsercenterFavoritesPageRouteImport.update({
    id: '/favorites/$page',
    path: '/favorites/$page',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boardlist': typeof BoardlistRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/newtopics': typeof NewtopicsRoute
  '/privacy': typeof PrivacyRoute
  '/recommendedtopics': typeof RecommendedtopicsRoute
  '/search': typeof SearchRoute
  '/following': typeof AuthenticatedFollowingRouteWithChildren
  '/following-topics': typeof AuthenticatedFollowingTopicsRoute
  '/message': typeof AuthenticatedMessageRouteWithChildren
  '/new-topic': typeof AuthenticatedNewTopicRoute
  '/usercenter': typeof AuthenticatedUsercenterRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/topic/$topicId': typeof TopicTopicIdRouteWithChildren
  '/following/boards': typeof AuthenticatedFollowingBoardsRoute
  '/following/users': typeof AuthenticatedFollowingUsersRoute
  '/message/at': typeof AuthenticatedMessageAtRoute
  '/message/private': typeof AuthenticatedMessagePrivateRoute
  '/message/reply': typeof AuthenticatedMessageReplyRoute
  '/message/system': typeof AuthenticatedMessageSystemRoute
  '/usercenter/edit': typeof AuthenticatedUsercenterEditRoute
  '/usercenter/fans': typeof AuthenticatedUsercenterFansRoute
  '/usercenter/followed-boards': typeof AuthenticatedUsercenterFollowedBoardsRoute
  '/usercenter/signin': typeof AuthenticatedUsercenterSigninRoute
  '/usercenter/theme': typeof AuthenticatedUsercenterThemeRoute
  '/usercenter/transfer': typeof AuthenticatedUsercenterTransferRoute
  '/user/id/$id': typeof UserIdIdRoute
  '/following/': typeof AuthenticatedFollowingIndexRoute
  '/message/': typeof AuthenticatedMessageIndexRoute
  '/usercenter/': typeof AuthenticatedUsercenterIndexRoute
  '/usercenter/favorites/$page': typeof AuthenticatedUsercenterFavoritesPageRoute
  '/usercenter/myposts/$page': typeof AuthenticatedUsercenterMypostsPageRoute
  '/usercenter/mytopics/$page': typeof AuthenticatedUsercenterMytopicsPageRoute
  '/topic/$topicId/trace/$userId': typeof TopicTopicIdTraceUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boardlist': typeof BoardlistRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/newtopics': typeof NewtopicsRoute
  '/privacy': typeof PrivacyRoute
  '/recommendedtopics': typeof RecommendedtopicsRoute
  '/search': typeof SearchRoute
  '/following-topics': typeof AuthenticatedFollowingTopicsRoute
  '/new-topic': typeof AuthenticatedNewTopicRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/topic/$topicId': typeof TopicTopicIdRouteWithChildren
  '/following/boards': typeof AuthenticatedFollowingBoardsRoute
  '/following/users': typeof AuthenticatedFollowingUsersRoute
  '/message/at': typeof AuthenticatedMessageAtRoute
  '/message/private': typeof AuthenticatedMessagePrivateRoute
  '/message/reply': typeof AuthenticatedMessageReplyRoute
  '/message/system': typeof AuthenticatedMessageSystemRoute
  '/usercenter/edit': typeof AuthenticatedUsercenterEditRoute
  '/usercenter/fans': typeof AuthenticatedUsercenterFansRoute
  '/usercenter/followed-boards': typeof AuthenticatedUsercenterFollowedBoardsRoute
  '/usercenter/signin': typeof AuthenticatedUsercenterSigninRoute
  '/usercenter/theme': typeof AuthenticatedUsercenterThemeRoute
  '/usercenter/transfer': typeof AuthenticatedUsercenterTransferRoute
  '/user/id/$id': typeof UserIdIdRoute
  '/following': typeof AuthenticatedFollowingIndexRoute
  '/message': typeof AuthenticatedMessageIndexRoute
  '/usercenter': typeof AuthenticatedUsercenterIndexRoute
  '/usercenter/favorites/$page': typeof AuthenticatedUsercenterFavoritesPageRoute
  '/usercenter/myposts/$page': typeof AuthenticatedUsercenterMypostsPageRoute
  '/usercenter/mytopics/$page': typeof AuthenticatedUsercenterMytopicsPageRoute
  '/topic/$topicId/trace/$userId': typeof TopicTopicIdTraceUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/boardlist': typeof BoardlistRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/newtopics': typeof NewtopicsRoute
  '/privacy': typeof PrivacyRoute
  '/recommendedtopics': typeof RecommendedtopicsRoute
  '/search': typeof SearchRoute
  '/_authenticated/following': typeof AuthenticatedFollowingRouteWithChildren
  '/_authenticated/following-topics': typeof AuthenticatedFollowingTopicsRoute
  '/_authenticated/message': typeof AuthenticatedMessageRouteWithChildren
  '/_authenticated/new-topic': typeof AuthenticatedNewTopicRoute
  '/_authenticated/usercenter': typeof AuthenticatedUsercenterRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/topic/$topicId': typeof TopicTopicIdRouteWithChildren
  '/_authenticated/following/boards': typeof AuthenticatedFollowingBoardsRoute
  '/_authenticated/following/users': typeof AuthenticatedFollowingUsersRoute
  '/_authenticated/message/at': typeof AuthenticatedMessageAtRoute
  '/_authenticated/message/private': typeof AuthenticatedMessagePrivateRoute
  '/_authenticated/message/reply': typeof AuthenticatedMessageReplyRoute
  '/_authenticated/message/system': typeof AuthenticatedMessageSystemRoute
  '/_authenticated/usercenter/edit': typeof AuthenticatedUsercenterEditRoute
  '/_authenticated/usercenter/fans': typeof AuthenticatedUsercenterFansRoute
  '/_authenticated/usercenter/followed-boards': typeof AuthenticatedUsercenterFollowedBoardsRoute
  '/_authenticated/usercenter/signin': typeof AuthenticatedUsercenterSigninRoute
  '/_authenticated/usercenter/theme': typeof AuthenticatedUsercenterThemeRoute
  '/_authenticated/usercenter/transfer': typeof AuthenticatedUsercenterTransferRoute
  '/user/id/$id': typeof UserIdIdRoute
  '/_authenticated/following/': typeof AuthenticatedFollowingIndexRoute
  '/_authenticated/message/': typeof AuthenticatedMessageIndexRoute
  '/_authenticated/usercenter/': typeof AuthenticatedUsercenterIndexRoute
  '/_authenticated/usercenter/favorites/$page': typeof AuthenticatedUsercenterFavoritesPageRoute
  '/_authenticated/usercenter/myposts/$page': typeof AuthenticatedUsercenterMypostsPageRoute
  '/_authenticated/usercenter/mytopics/$page': typeof AuthenticatedUsercenterMytopicsPageRoute
  '/topic/$topicId/trace/$userId': typeof TopicTopicIdTraceUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/boardlist'
    | '/contact'
    | '/login'
    | '/newtopics'
    | '/privacy'
    | '/recommendedtopics'
    | '/search'
    | '/following'
    | '/following-topics'
    | '/message'
    | '/new-topic'
    | '/usercenter'
    | '/auth/callback'
    | '/board/$boardId'
    | '/topic/$topicId'
    | '/following/boards'
    | '/following/users'
    | '/message/at'
    | '/message/private'
    | '/message/reply'
    | '/message/system'
    | '/usercenter/edit'
    | '/usercenter/fans'
    | '/usercenter/followed-boards'
    | '/usercenter/signin'
    | '/usercenter/theme'
    | '/usercenter/transfer'
    | '/user/id/$id'
    | '/following/'
    | '/message/'
    | '/usercenter/'
    | '/usercenter/favorites/$page'
    | '/usercenter/myposts/$page'
    | '/usercenter/mytopics/$page'
    | '/topic/$topicId/trace/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/boardlist'
    | '/contact'
    | '/login'
    | '/newtopics'
    | '/privacy'
    | '/recommendedtopics'
    | '/search'
    | '/following-topics'
    | '/new-topic'
    | '/auth/callback'
    | '/board/$boardId'
    | '/topic/$topicId'
    | '/following/boards'
    | '/following/users'
    | '/message/at'
    | '/message/private'
    | '/message/reply'
    | '/message/system'
    | '/usercenter/edit'
    | '/usercenter/fans'
    | '/usercenter/followed-boards'
    | '/usercenter/signin'
    | '/usercenter/theme'
    | '/usercenter/transfer'
    | '/user/id/$id'
    | '/following'
    | '/message'
    | '/usercenter'
    | '/usercenter/favorites/$page'
    | '/usercenter/myposts/$page'
    | '/usercenter/mytopics/$page'
    | '/topic/$topicId/trace/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/boardlist'
    | '/contact'
    | '/login'
    | '/newtopics'
    | '/privacy'
    | '/recommendedtopics'
    | '/search'
    | '/_authenticated/following'
    | '/_authenticated/following-topics'
    | '/_authenticated/message'
    | '/_authenticated/new-topic'
    | '/_authenticated/usercenter'
    | '/auth/callback'
    | '/board/$boardId'
    | '/topic/$topicId'
    | '/_authenticated/following/boards'
    | '/_authenticated/following/users'
    | '/_authenticated/message/at'
    | '/_authenticated/message/private'
    | '/_authenticated/message/reply'
    | '/_authenticated/message/system'
    | '/_authenticated/usercenter/edit'
    | '/_authenticated/usercenter/fans'
    | '/_authenticated/usercenter/followed-boards'
    | '/_authenticated/usercenter/signin'
    | '/_authenticated/usercenter/theme'
    | '/_authenticated/usercenter/transfer'
    | '/user/id/$id'
    | '/_authenticated/following/'
    | '/_authenticated/message/'
    | '/_authenticated/usercenter/'
    | '/_authenticated/usercenter/favorites/$page'
    | '/_authenticated/usercenter/myposts/$page'
    | '/_authenticated/usercenter/mytopics/$page'
    | '/topic/$topicId/trace/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BoardlistRoute: typeof BoardlistRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  NewtopicsRoute: typeof NewtopicsRoute
  PrivacyRoute: typeof PrivacyRoute
  RecommendedtopicsRoute: typeof RecommendedtopicsRoute
  SearchRoute: typeof SearchRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  TopicTopicIdRoute: typeof TopicTopicIdRouteWithChildren
  UserIdIdRoute: typeof UserIdIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendedtopics': {
      id: '/recommendedtopics'
      path: '/recommendedtopics'
      fullPath: '/recommendedtopics'
      preLoaderRoute: typeof RecommendedtopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newtopics': {
      id: '/newtopics'
      path: '/newtopics'
      fullPath: '/newtopics'
      preLoaderRoute: typeof NewtopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boardlist': {
      id: '/boardlist'
      path: '/boardlist'
      fullPath: '/boardlist'
      preLoaderRoute: typeof BoardlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usercenter': {
      id: '/_authenticated/usercenter'
      path: '/usercenter'
      fullPath: '/usercenter'
      preLoaderRoute: typeof AuthenticatedUsercenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new-topic': {
      id: '/_authenticated/new-topic'
      path: '/new-topic'
      fullPath: '/new-topic'
      preLoaderRoute: typeof AuthenticatedNewTopicRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/message': {
      id: '/_authenticated/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof AuthenticatedMessageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/following-topics': {
      id: '/_authenticated/following-topics'
      path: '/following-topics'
      fullPath: '/following-topics'
      preLoaderRoute: typeof AuthenticatedFollowingTopicsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/following': {
      id: '/_authenticated/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof AuthenticatedFollowingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usercenter/': {
      id: '/_authenticated/usercenter/'
      path: '/'
      fullPath: '/usercenter/'
      preLoaderRoute: typeof AuthenticatedUsercenterIndexRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
    '/_authenticated/message/': {
      id: '/_authenticated/message/'
      path: '/'
      fullPath: '/message/'
      preLoaderRoute: typeof AuthenticatedMessageIndexRouteImport
      parentRoute: typeof AuthenticatedMessageRoute
    }
    '/_authenticated/following/': {
      id: '/_authenticated/following/'
      path: '/'
      fullPath: '/following/'
      preLoaderRoute: typeof AuthenticatedFollowingIndexRouteImport
      parentRoute: typeof AuthenticatedFollowingRoute
    }
    '/user/id/$id': {
      id: '/user/id/$id'
      path: '/user/id/$id'
      fullPath: '/user/id/$id'
      preLoaderRoute: typeof UserIdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usercenter/transfer': {
      id: '/_authenticated/usercenter/transfer'
      path: '/transfer'
      fullPath: '/usercenter/transfer'
      preLoaderRoute: typeof AuthenticatedUsercenterTransferRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
    '/_authenticated/usercenter/theme': {
      id: '/_authenticated/usercenter/theme'
      path: '/theme'
      fullPath: '/usercenter/theme'
      preLoaderRoute: typeof AuthenticatedUsercenterThemeRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
    '/_authenticated/usercenter/signin': {
      id: '/_authenticated/usercenter/signin'
      path: '/signin'
      fullPath: '/usercenter/signin'
      preLoaderRoute: typeof AuthenticatedUsercenterSigninRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
    '/_authenticated/usercenter/followed-boards': {
      id: '/_authenticated/usercenter/followed-boards'
      path: '/followed-boards'
      fullPath: '/usercenter/followed-boards'
      preLoaderRoute: typeof AuthenticatedUsercenterFollowedBoardsRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
    '/_authenticated/usercenter/fans': {
      id: '/_authenticated/usercenter/fans'
      path: '/fans'
      fullPath: '/usercenter/fans'
      preLoaderRoute: typeof AuthenticatedUsercenterFansRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
    '/_authenticated/usercenter/edit': {
      id: '/_authenticated/usercenter/edit'
      path: '/edit'
      fullPath: '/usercenter/edit'
      preLoaderRoute: typeof AuthenticatedUsercenterEditRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
    '/_authenticated/message/system': {
      id: '/_authenticated/message/system'
      path: '/system'
      fullPath: '/message/system'
      preLoaderRoute: typeof AuthenticatedMessageSystemRouteImport
      parentRoute: typeof AuthenticatedMessageRoute
    }
    '/_authenticated/message/reply': {
      id: '/_authenticated/message/reply'
      path: '/reply'
      fullPath: '/message/reply'
      preLoaderRoute: typeof AuthenticatedMessageReplyRouteImport
      parentRoute: typeof AuthenticatedMessageRoute
    }
    '/_authenticated/message/private': {
      id: '/_authenticated/message/private'
      path: '/private'
      fullPath: '/message/private'
      preLoaderRoute: typeof AuthenticatedMessagePrivateRouteImport
      parentRoute: typeof AuthenticatedMessageRoute
    }
    '/_authenticated/message/at': {
      id: '/_authenticated/message/at'
      path: '/at'
      fullPath: '/message/at'
      preLoaderRoute: typeof AuthenticatedMessageAtRouteImport
      parentRoute: typeof AuthenticatedMessageRoute
    }
    '/_authenticated/following/users': {
      id: '/_authenticated/following/users'
      path: '/users'
      fullPath: '/following/users'
      preLoaderRoute: typeof AuthenticatedFollowingUsersRouteImport
      parentRoute: typeof AuthenticatedFollowingRoute
    }
    '/_authenticated/following/boards': {
      id: '/_authenticated/following/boards'
      path: '/boards'
      fullPath: '/following/boards'
      preLoaderRoute: typeof AuthenticatedFollowingBoardsRouteImport
      parentRoute: typeof AuthenticatedFollowingRoute
    }
    '/topic/$topicId/trace/$userId': {
      id: '/topic/$topicId/trace/$userId'
      path: '/trace/$userId'
      fullPath: '/topic/$topicId/trace/$userId'
      preLoaderRoute: typeof TopicTopicIdTraceUserIdRouteImport
      parentRoute: typeof TopicTopicIdRoute
    }
    '/_authenticated/usercenter/mytopics/$page': {
      id: '/_authenticated/usercenter/mytopics/$page'
      path: '/mytopics/$page'
      fullPath: '/usercenter/mytopics/$page'
      preLoaderRoute: typeof AuthenticatedUsercenterMytopicsPageRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
    '/_authenticated/usercenter/myposts/$page': {
      id: '/_authenticated/usercenter/myposts/$page'
      path: '/myposts/$page'
      fullPath: '/usercenter/myposts/$page'
      preLoaderRoute: typeof AuthenticatedUsercenterMypostsPageRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
    '/_authenticated/usercenter/favorites/$page': {
      id: '/_authenticated/usercenter/favorites/$page'
      path: '/favorites/$page'
      fullPath: '/usercenter/favorites/$page'
      preLoaderRoute: typeof AuthenticatedUsercenterFavoritesPageRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
  }
}

interface AuthenticatedFollowingRouteChildren {
  AuthenticatedFollowingBoardsRoute: typeof AuthenticatedFollowingBoardsRoute
  AuthenticatedFollowingUsersRoute: typeof AuthenticatedFollowingUsersRoute
  AuthenticatedFollowingIndexRoute: typeof AuthenticatedFollowingIndexRoute
}

const AuthenticatedFollowingRouteChildren: AuthenticatedFollowingRouteChildren =
  {
    AuthenticatedFollowingBoardsRoute: AuthenticatedFollowingBoardsRoute,
    AuthenticatedFollowingUsersRoute: AuthenticatedFollowingUsersRoute,
    AuthenticatedFollowingIndexRoute: AuthenticatedFollowingIndexRoute,
  }

const AuthenticatedFollowingRouteWithChildren =
  AuthenticatedFollowingRoute._addFileChildren(
    AuthenticatedFollowingRouteChildren,
  )

interface AuthenticatedMessageRouteChildren {
  AuthenticatedMessageAtRoute: typeof AuthenticatedMessageAtRoute
  AuthenticatedMessagePrivateRoute: typeof AuthenticatedMessagePrivateRoute
  AuthenticatedMessageReplyRoute: typeof AuthenticatedMessageReplyRoute
  AuthenticatedMessageSystemRoute: typeof AuthenticatedMessageSystemRoute
  AuthenticatedMessageIndexRoute: typeof AuthenticatedMessageIndexRoute
}

const AuthenticatedMessageRouteChildren: AuthenticatedMessageRouteChildren = {
  AuthenticatedMessageAtRoute: AuthenticatedMessageAtRoute,
  AuthenticatedMessagePrivateRoute: AuthenticatedMessagePrivateRoute,
  AuthenticatedMessageReplyRoute: AuthenticatedMessageReplyRoute,
  AuthenticatedMessageSystemRoute: AuthenticatedMessageSystemRoute,
  AuthenticatedMessageIndexRoute: AuthenticatedMessageIndexRoute,
}

const AuthenticatedMessageRouteWithChildren =
  AuthenticatedMessageRoute._addFileChildren(AuthenticatedMessageRouteChildren)

interface AuthenticatedUsercenterRouteChildren {
  AuthenticatedUsercenterEditRoute: typeof AuthenticatedUsercenterEditRoute
  AuthenticatedUsercenterFansRoute: typeof AuthenticatedUsercenterFansRoute
  AuthenticatedUsercenterFollowedBoardsRoute: typeof AuthenticatedUsercenterFollowedBoardsRoute
  AuthenticatedUsercenterSigninRoute: typeof AuthenticatedUsercenterSigninRoute
  AuthenticatedUsercenterThemeRoute: typeof AuthenticatedUsercenterThemeRoute
  AuthenticatedUsercenterTransferRoute: typeof AuthenticatedUsercenterTransferRoute
  AuthenticatedUsercenterIndexRoute: typeof AuthenticatedUsercenterIndexRoute
  AuthenticatedUsercenterFavoritesPageRoute: typeof AuthenticatedUsercenterFavoritesPageRoute
  AuthenticatedUsercenterMypostsPageRoute: typeof AuthenticatedUsercenterMypostsPageRoute
  AuthenticatedUsercenterMytopicsPageRoute: typeof AuthenticatedUsercenterMytopicsPageRoute
}

const AuthenticatedUsercenterRouteChildren: AuthenticatedUsercenterRouteChildren =
  {
    AuthenticatedUsercenterEditRoute: AuthenticatedUsercenterEditRoute,
    AuthenticatedUsercenterFansRoute: AuthenticatedUsercenterFansRoute,
    AuthenticatedUsercenterFollowedBoardsRoute:
      AuthenticatedUsercenterFollowedBoardsRoute,
    AuthenticatedUsercenterSigninRoute: AuthenticatedUsercenterSigninRoute,
    AuthenticatedUsercenterThemeRoute: AuthenticatedUsercenterThemeRoute,
    AuthenticatedUsercenterTransferRoute: AuthenticatedUsercenterTransferRoute,
    AuthenticatedUsercenterIndexRoute: AuthenticatedUsercenterIndexRoute,
    AuthenticatedUsercenterFavoritesPageRoute:
      AuthenticatedUsercenterFavoritesPageRoute,
    AuthenticatedUsercenterMypostsPageRoute:
      AuthenticatedUsercenterMypostsPageRoute,
    AuthenticatedUsercenterMytopicsPageRoute:
      AuthenticatedUsercenterMytopicsPageRoute,
  }

const AuthenticatedUsercenterRouteWithChildren =
  AuthenticatedUsercenterRoute._addFileChildren(
    AuthenticatedUsercenterRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedFollowingRoute: typeof AuthenticatedFollowingRouteWithChildren
  AuthenticatedFollowingTopicsRoute: typeof AuthenticatedFollowingTopicsRoute
  AuthenticatedMessageRoute: typeof AuthenticatedMessageRouteWithChildren
  AuthenticatedNewTopicRoute: typeof AuthenticatedNewTopicRoute
  AuthenticatedUsercenterRoute: typeof AuthenticatedUsercenterRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFollowingRoute: AuthenticatedFollowingRouteWithChildren,
  AuthenticatedFollowingTopicsRoute: AuthenticatedFollowingTopicsRoute,
  AuthenticatedMessageRoute: AuthenticatedMessageRouteWithChildren,
  AuthenticatedNewTopicRoute: AuthenticatedNewTopicRoute,
  AuthenticatedUsercenterRoute: AuthenticatedUsercenterRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface TopicTopicIdRouteChildren {
  TopicTopicIdTraceUserIdRoute: typeof TopicTopicIdTraceUserIdRoute
}

const TopicTopicIdRouteChildren: TopicTopicIdRouteChildren = {
  TopicTopicIdTraceUserIdRoute: TopicTopicIdTraceUserIdRoute,
}

const TopicTopicIdRouteWithChildren = TopicTopicIdRoute._addFileChildren(
  TopicTopicIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BoardlistRoute: BoardlistRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  NewtopicsRoute: NewtopicsRoute,
  PrivacyRoute: PrivacyRoute,
  RecommendedtopicsRoute: RecommendedtopicsRoute,
  SearchRoute: SearchRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  TopicTopicIdRoute: TopicTopicIdRouteWithChildren,
  UserIdIdRoute: UserIdIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
