/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendedtopicsRouteImport } from './routes/recommendedtopics'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewtopicsRouteImport } from './routes/newtopics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BoardlistRouteImport } from './routes/boardlist'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicTopicIdRouteImport } from './routes/topic/$topicId'
import { Route as BoardBoardIdRouteImport } from './routes/board/$boardId'
import { Route as AuthenticatedUsercenterRouteImport } from './routes/_authenticated/usercenter'
import { Route as AuthenticatedMessageRouteImport } from './routes/_authenticated/message'
import { Route as AuthenticatedUsercenterMytopicsPageRouteImport } from './routes/_authenticated/usercenter.mytopics.$page'
import { Route as AuthenticatedUsercenterMypostsPageRouteImport } from './routes/_authenticated/usercenter.myposts.$page'

const RecommendedtopicsRoute = RecommendedtopicsRouteImport.update({
  id: '/recommendedtopics',
  path: '/recommendedtopics',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewtopicsRoute = NewtopicsRouteImport.update({
  id: '/newtopics',
  path: '/newtopics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardlistRoute = BoardlistRouteImport.update({
  id: '/boardlist',
  path: '/boardlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsercenterRoute = AuthenticatedUsercenterRouteImport.update({
  id: '/usercenter',
  path: '/usercenter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessageRoute = AuthenticatedMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsercenterMytopicsPageRoute =
  AuthenticatedUsercenterMytopicsPageRouteImport.update({
    id: '/mytopics/$page',
    path: '/mytopics/$page',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)
const AuthenticatedUsercenterMypostsPageRoute =
  AuthenticatedUsercenterMypostsPageRouteImport.update({
    id: '/myposts/$page',
    path: '/myposts/$page',
    getParentRoute: () => AuthenticatedUsercenterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boardlist': typeof BoardlistRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/newtopics': typeof NewtopicsRoute
  '/privacy': typeof PrivacyRoute
  '/recommendedtopics': typeof RecommendedtopicsRoute
  '/message': typeof AuthenticatedMessageRoute
  '/usercenter': typeof AuthenticatedUsercenterRouteWithChildren
  '/board/$boardId': typeof BoardBoardIdRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/usercenter/myposts/$page': typeof AuthenticatedUsercenterMypostsPageRoute
  '/usercenter/mytopics/$page': typeof AuthenticatedUsercenterMytopicsPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boardlist': typeof BoardlistRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/newtopics': typeof NewtopicsRoute
  '/privacy': typeof PrivacyRoute
  '/recommendedtopics': typeof RecommendedtopicsRoute
  '/message': typeof AuthenticatedMessageRoute
  '/usercenter': typeof AuthenticatedUsercenterRouteWithChildren
  '/board/$boardId': typeof BoardBoardIdRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/usercenter/myposts/$page': typeof AuthenticatedUsercenterMypostsPageRoute
  '/usercenter/mytopics/$page': typeof AuthenticatedUsercenterMytopicsPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/boardlist': typeof BoardlistRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/newtopics': typeof NewtopicsRoute
  '/privacy': typeof PrivacyRoute
  '/recommendedtopics': typeof RecommendedtopicsRoute
  '/_authenticated/message': typeof AuthenticatedMessageRoute
  '/_authenticated/usercenter': typeof AuthenticatedUsercenterRouteWithChildren
  '/board/$boardId': typeof BoardBoardIdRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
  '/_authenticated/usercenter/myposts/$page': typeof AuthenticatedUsercenterMypostsPageRoute
  '/_authenticated/usercenter/mytopics/$page': typeof AuthenticatedUsercenterMytopicsPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/boardlist'
    | '/contact'
    | '/login'
    | '/newtopics'
    | '/privacy'
    | '/recommendedtopics'
    | '/message'
    | '/usercenter'
    | '/board/$boardId'
    | '/topic/$topicId'
    | '/usercenter/myposts/$page'
    | '/usercenter/mytopics/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/boardlist'
    | '/contact'
    | '/login'
    | '/newtopics'
    | '/privacy'
    | '/recommendedtopics'
    | '/message'
    | '/usercenter'
    | '/board/$boardId'
    | '/topic/$topicId'
    | '/usercenter/myposts/$page'
    | '/usercenter/mytopics/$page'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/boardlist'
    | '/contact'
    | '/login'
    | '/newtopics'
    | '/privacy'
    | '/recommendedtopics'
    | '/_authenticated/message'
    | '/_authenticated/usercenter'
    | '/board/$boardId'
    | '/topic/$topicId'
    | '/_authenticated/usercenter/myposts/$page'
    | '/_authenticated/usercenter/mytopics/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BoardlistRoute: typeof BoardlistRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  NewtopicsRoute: typeof NewtopicsRoute
  PrivacyRoute: typeof PrivacyRoute
  RecommendedtopicsRoute: typeof RecommendedtopicsRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendedtopics': {
      id: '/recommendedtopics'
      path: '/recommendedtopics'
      fullPath: '/recommendedtopics'
      preLoaderRoute: typeof RecommendedtopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newtopics': {
      id: '/newtopics'
      path: '/newtopics'
      fullPath: '/newtopics'
      preLoaderRoute: typeof NewtopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boardlist': {
      id: '/boardlist'
      path: '/boardlist'
      fullPath: '/boardlist'
      preLoaderRoute: typeof BoardlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usercenter': {
      id: '/_authenticated/usercenter'
      path: '/usercenter'
      fullPath: '/usercenter'
      preLoaderRoute: typeof AuthenticatedUsercenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/message': {
      id: '/_authenticated/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof AuthenticatedMessageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usercenter/mytopics/$page': {
      id: '/_authenticated/usercenter/mytopics/$page'
      path: '/mytopics/$page'
      fullPath: '/usercenter/mytopics/$page'
      preLoaderRoute: typeof AuthenticatedUsercenterMytopicsPageRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
    '/_authenticated/usercenter/myposts/$page': {
      id: '/_authenticated/usercenter/myposts/$page'
      path: '/myposts/$page'
      fullPath: '/usercenter/myposts/$page'
      preLoaderRoute: typeof AuthenticatedUsercenterMypostsPageRouteImport
      parentRoute: typeof AuthenticatedUsercenterRoute
    }
  }
}

interface AuthenticatedUsercenterRouteChildren {
  AuthenticatedUsercenterMypostsPageRoute: typeof AuthenticatedUsercenterMypostsPageRoute
  AuthenticatedUsercenterMytopicsPageRoute: typeof AuthenticatedUsercenterMytopicsPageRoute
}

const AuthenticatedUsercenterRouteChildren: AuthenticatedUsercenterRouteChildren = {
  AuthenticatedUsercenterMypostsPageRoute: AuthenticatedUsercenterMypostsPageRoute,
  AuthenticatedUsercenterMytopicsPageRoute: AuthenticatedUsercenterMytopicsPageRoute,
}

const AuthenticatedUsercenterRouteWithChildren = AuthenticatedUsercenterRoute._addFileChildren(
  AuthenticatedUsercenterRouteChildren
)

interface AuthenticatedRouteChildren {
  AuthenticatedMessageRoute: typeof AuthenticatedMessageRoute
  AuthenticatedUsercenterRoute: typeof AuthenticatedUsercenterRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMessageRoute: AuthenticatedMessageRoute,
  AuthenticatedUsercenterRoute: AuthenticatedUsercenterRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BoardlistRoute: BoardlistRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  NewtopicsRoute: NewtopicsRoute,
  PrivacyRoute: PrivacyRoute,
  RecommendedtopicsRoute: RecommendedtopicsRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
